# Generated by Django 3.0.6 on 2020-06-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treina_Facil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_do_treinamento', models.CharField(max_length=50)),
                ('Exerc_1', models.CharField(max_length=50)),
                ('Exerc_2', models.CharField(max_length=50)),
                ('Exerc_3', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'treinamento facil',
            },
        ),
    ]
