# Generated by Django 3.0.6 on 2020-06-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Treino', models.CharField(max_length=50)),
                ('Quant', models.IntegerField()),
                ('Cpf', models.IntegerField()),
                ('Preco', models.IntegerField()),
            ],
            options={
                'db_table': 'Assinar',
            },
        ),
    ]
